Database XSS - SQL Injection/M183-SQL Injection/M183-TwoWayAuth/Controllers/MainController.cs
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.IO;
using System.Linq;
using System.Net;
using System.Text;
using System.Web;
using System.Web.Mvc;

namespace M183_SQLInjection.Controllers
{
    public class MainController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Token()
        {
            return View();
        }

        public ActionResult Feedback()
        {
            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }

        [HttpPost]
        public ActionResult Login()
        {
            var usernameFromView = Request["username"];
            var passwordFromView = Request["password"];

            SqlConnection con = new SqlConnection();
            con.ConnectionString = "Data Source=(LocalDB)\\MSSQLLocalDB;AttachDbFilename=C:\\Users\\Sean\\Documents\\sql_xss_injection.mdf;Integrated Security=True;Connect Timeout=30"; //TODO Connectionstring anpassen!
            SqlCommand cmd = new SqlCommand();
            SqlDataReader reader;

            cmd.CommandText = "SELECT [Id] ,[username] , [password] FROM [dbo].[User] WHERE [username] = '" + usernameFromView + "' AND [password] = '" + passwordFromView + "'";
            cmd.Connection = con;
            con.Open();
            reader = cmd.ExecuteReader();
            if (reader.HasRows)
            {
                ViewBag.Message = "Return from Database: ";
                while (reader.Read())
                {
                    ViewBag.Message += reader.GetInt32(0) + " " + reader.GetString(2) + " " + reader.GetString(2) + ", ";
                }
            }
            else
            {
                ViewBag.Message = "Failed.";
            }
            return View("~/Views/Main/Index.cshtml");
        }

        [HttpPost]
        public ActionResult FeedbackSubmit()
        {
            var feedbackFromView = Request["feedback"];
            string connetionString = "Data Source=(LocalDB)\\MSSQLLocalDB;AttachDbFilename=C:\\Users\\Jerome\\Documents\\sql_xss_injection.mdf;Integrated Security=True;Connect Timeout=30"; //TODO Connectionstring anpassen!
            string sqlQuery = "INSERT INTO Feedback ([feedback]) values(@value)";
            SqlDataAdapter adapter = new SqlDataAdapter();
            using (SqlConnection con = new SqlConnection(connetionString))
            {
                con.Open();
                using (SqlCommand cmd = new SqlCommand(sqlQuery, con))
                {
                    cmd.Parameters.AddWithValue("@value", feedbackFromView);
                    cmd.ExecuteNonQuery();
                    ViewBag.Message = "Data Added";
                }
            }

            return View("~/Views/Main/Feedback.cshtml");
        }
    }
}

Database XSS - SQL Injection/M183-SQL Injection/M183-TwoWayAuth/Views/Main/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Database XSS - SQL Injection/M183-SQL Injection/M183-TwoWayAuth/Views/Main/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Database XSS - SQL Injection/M183-SQL Injection/M183-TwoWayAuth/Views/Main/Feedback.cshtml
@{
    ViewBag.Title = "Feedback Page";
}

<div class="row" style="margin-top:80px;">
    <div class="col-lg-8 col-lg-offset-2">
        <form action="./FeedbackSubmit" method="post" class="well col-lg-8 col-lg-offset-2" style="margin-top:60px;">
            <label>Feedback</label>
            <textarea name="feedback" class="form-control"></textarea>
            <input type="submit" name="submit" value="Submit" class="btn btn btn-primary" />
            @ViewBag.Message
        </form>
    </div>
</div>

Database XSS - SQL Injection/M183-SQL Injection/M183-TwoWayAuth/Views/Main/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="row" style="margin-top:80px;">
    <div class="col-lg-8 col-lg-offset-2">
        <legend>Log In</legend>
        <form class="well" action="./Main/Login" method="post">
            <legend><small>Username</small></legend>
            <input type="text" name="username" value="" class="form-control" />
            <br />
            <legend><small>Password</small></legend>
            <input type="password" name="password" value="" class="form-control" />
            <br />
            <input type="submit" name="submit" value="Log In" class="btn btn-primary" />
            @ViewBag.Message
        </form>
    </div>
</div>

Database XSS - SQL Injection/M183-SQL Injection/M183-TwoWayAuth/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Meine ASP.NET-Anwendung</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Anwendungsname", "Index", "Main", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Login", "Index", "Main")</li>
                    <li>@Html.ActionLink("Feedback", "Feedback", "Main")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        <small style="color:red;">Dont forget to edit Connectionstring in MainController</small>
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Meine ASP.NET-Anwendung</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>